### ISSUE TITLE
Error Installing on conda

### ISSUE THREAD

**Issue by mohnark** [centreborelli/s2p#106]
I have a conda venv and installed packages:
  Gdal 3.3.2
  Rasterio 1.2.10 
  Fftw 3.3.9
  Libgdal 3.3.2
  libtiff 4.3.0

I attempt to install s2p using "pip install s2p"

Logs: \

_Collecting s2p
  Using cached s2p-1.0b25.tar.gz (663 kB)
Requirement already satisfied: numpy in d:\programs\anaconda\envs\bunnies\lib\site-packages (from s2p) (1.21.2)
Collecting scipy
  Using cached scipy-1.7.1-cp37-cp37m-win_amd64.whl (33.6 MB)
Requirement already satisfied: rasterio[s3]>=1.0.14 in d:\programs\anaconda\envs\bunnies\lib\site-packages (from s2p) (1.2.10)
Collecting utm
  Using cached utm-0.7.0-py3-none-any.whl
Collecting pyproj<3.0.0,>=2.0.2
  Using cached pyproj-2.6.1.post1-cp37-cp37m-win_amd64.whl (17.2 MB)
Collecting beautifulsoup4[lxml]
  Using cached beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
Collecting plyfile
  Using cached plyfile-0.7.4-py3-none-any.whl (39 kB)
Collecting plyflatten>=0.2.0
  Using cached plyflatten-0.2.0.tar.gz (8.9 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting ransac
  Using cached ransac-1.0.4.tar.gz (31 kB)
Collecting rpcm>=1.4.6
  Using cached rpcm-1.4.7-py3-none-any.whl (16 kB)
Collecting srtm4>=1.1.2
  Using cached srtm4-1.1.5.tar.gz (2.0 MB)
Collecting requests
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Requirement already satisfied: affine in d:\programs\anaconda\envs\bunnies\lib\site-packages (from plyflatten>=0.2.0->s2p) (2.3.0)
Requirement already satisfied: attrs in d:\programs\anaconda\envs\bunnies\lib\site-packages (from rasterio[s3]>=1.0.14->s2p) (21.2.0)
Requirement already satisfied: certifi in d:\programs\anaconda\envs\bunnies\lib\site-packages (from rasterio[s3]>=1.0.14->s2p) (2021.10.8)
Requirement already satisfied: click>=4.0 in d:\programs\anaconda\envs\bunnies\lib\site-packages (from rasterio[s3]>=1.0.14->s2p) (8.0.3)
Requirement already satisfied: cligj>=0.5 in d:\programs\anaconda\envs\bunnies\lib\site-packages (from rasterio[s3]>=1.0.14->s2p) (0.7.2)
Requirement already satisfied: snuggs>=1.4.1 in d:\programs\anaconda\envs\bunnies\lib\site-packages (from rasterio[s3]>=1.0.14->s2p) (1.4.7)
Requirement already satisfied: click-plugins in d:\programs\anaconda\envs\bunnies\lib\site-packages (from rasterio[s3]>=1.0.14->s2p) (1.1.1)
Requirement already satisfied: setuptools in d:\programs\anaconda\envs\bunnies\lib\site-packages (from rasterio[s3]>=1.0.14->s2p) (58.0.4)
Collecting boto3>=1.2.4
  Downloading boto3-1.19.2-py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 1.1 MB/s
Collecting s3transfer<0.6.0,>=0.5.0
  Using cached s3transfer-0.5.0-py3-none-any.whl (79 kB)
Collecting jmespath<1.0.0,>=0.7.1
  Using cached jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting botocore<1.23.0,>=1.22.2
  Downloading botocore-1.22.2-py3-none-any.whl (8.0 MB)
     |████████████████████████████████| 8.0 MB 1.3 MB/s
Collecting python-dateutil<3.0.0,>=2.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting urllib3<1.27,>=1.25.4
  Using cached urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
Requirement already satisfied: colorama in d:\programs\anaconda\envs\bunnies\lib\site-packages (from click>=4.0->rasterio[s3]>=1.0.14->s2p) (0.4.4)
Requirement already satisfied: importlib-metadata in d:\programs\anaconda\envs\bunnies\lib\site-packages (from click>=4.0->rasterio[s3]>=1.0.14->s2p) (4.8.1)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting geojson
  Using cached geojson-2.5.0-py2.py3-none-any.whl (14 kB)
Requirement already satisfied: pyparsing>=2.1.6 in d:\programs\anaconda\envs\bunnies\lib\site-packages (from snuggs>=1.4.1->rasterio[s3]>=1.0.14->s2p) (2.4.7)
Collecting filelock
  Using cached filelock-3.3.1-py3-none-any.whl (9.7 kB)
Collecting soupsieve>1.2
  Using cached soupsieve-2.2.1-py3-none-any.whl (33 kB)
Collecting lxml
  Using cached lxml-4.6.3-cp37-cp37m-win_amd64.whl (3.5 MB)
Requirement already satisfied: typing-extensions>=3.6.4 in d:\programs\anaconda\envs\bunnies\lib\site-packages (from importlib-metadata->click>=4.0->rasterio[s3]>=1.0.14->s2p) (3.10.0.2)
Requirement already satisfied: zipp>=0.5 in d:\programs\anaconda\envs\bunnies\lib\site-packages (from importlib-metadata->click>=4.0->rasterio[s3]>=1.0.14->s2p) (3.6.0)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.7-py3-none-any.whl (38 kB)
Building wheels for collected packages: s2p, plyflatten, srtm4, ransac
  Building wheel for s2p (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\Programs\Anaconda\envs\bunnies\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kumai\\AppData\\Local\\Temp\\pip-install-smqym8p9\\s2p_2742f1c93e6845a78bcbda0fd22c8b3f\\setup.py'"'"'; __file__='"'"'C:\\Users\\kumai\\AppData\\Local\\Temp\\pip-install-smqym8p9\\s2p_2742f1c93e6845a78bcbda0fd22c8b3f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\kumai\AppData\Local\Temp\pip-wheel-fcjf89di'
       cwd: C:\Users\kumai\AppData\Local\Temp\pip-install-smqym8p9\s2p_2742f1c93e6845a78bcbda0fd22c8b3f\
  Complete output (93 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\s2p
  copying s2p\block_matching.py -> build\lib\s2p
  copying s2p\cli.py -> build\lib\s2p
  copying s2p\common.py -> build\lib\s2p
  copying s2p\config.py -> build\lib\s2p
  copying s2p\estimation.py -> build\lib\s2p
  copying s2p\evaluation.py -> build\lib\s2p
  copying s2p\fusion.py -> build\lib\s2p
  copying s2p\geographiclib.py -> build\lib\s2p
  copying s2p\initialization.py -> build\lib\s2p
  copying s2p\masking.py -> build\lib\s2p
  copying s2p\parallel.py -> build\lib\s2p
  copying s2p\ply.py -> build\lib\s2p
  copying s2p\pointing_accuracy.py -> build\lib\s2p
  copying s2p\rectification.py -> build\lib\s2p
  copying s2p\rpc_utils.py -> build\lib\s2p
  copying s2p\sift.py -> build\lib\s2p
  copying s2p\triangulation.py -> build\lib\s2p
  copying s2p\visualisation.py -> build\lib\s2p
  copying s2p\__init__.py -> build\lib\s2p
  The system cannot find the path specified.
  C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe -j -C 3rdparty/homography
  make[1]: Entering directory 'C:/Users/kumai/AppData/Local/Temp/pip-install-smqym8p9/s2p_2742f1c93e6845a78bcbda0fd22c8b3f/3rdparty/homography'
  The system cannot find the path specified.
  g++ -march=native -O3 `gdal-config --cflags`   -c -o main.o main.cpp
  g++ -march=native -O3 `gdal-config --cflags`   -c -o LibImages/LibImages.o LibImages/LibImages.cpp
  g++ -march=native -O3 `gdal-config --cflags`   -c -o Utilities/Utilities.o Utilities/Utilities.cpp
  g++ -march=native -O3 `gdal-config --cflags`   -c -o Utilities/Memory.o Utilities/Memory.cpp
  g++ -march=native -O3 `gdal-config --cflags`   -c -o Utilities/Parameters.o Utilities/Parameters.cpp
  g++ -march=native -O3 `gdal-config --cflags`   -c -o Utilities/Time.o Utilities/Time.cpp
  g++ -march=native -O3 `gdal-config --cflags`   -c -o LibHomography/Homography.o LibHomography/Homography.cpp
  g++ -march=native -O3 `gdal-config --cflags`   -c -o LibHomography/Splines.o LibHomography/Splines.cpp
  g++: error: `gdal-config: No such file or directory
  g++: error: `gdal-config: No such file or directory
  g++: error: unrecognized command line option '--cflags`'
  g++: error: `gdal-config: No such file or directory
  g++: error: unrecognized command line option '--cflags`'
  g++: error: unrecognized command line option '--cflags`'
  g++: error: `gdal-config: No such file or directory
  g++: error: `gdal-config: No such file or directory
  g++: error: `gdal-config: No such file or directory
  g++: error: unrecognized command line option '--cflags`'
  make[1]: *** [<builtin>: LibHomography/Splines.o] Error 1
  make[1]: *** Waiting for unfinished jobs....
  make[1]: *** [<builtin>: Utilities/Utilities.o] Error 1
  g++: error: unrecognized command line option '--cflags`'
  g++: error: unrecognized command line option '--cflags`'
  g++: error: `gdal-config: No such file or directory
  g++: error: `gdal-config: No such file or directory
  make[1]: *** [<builtin>: Utilities/Parameters.o] Error 1
  make[1]: *** [<builtin>: Utilities/Time.o] Error 1
  make[1]: *** [<builtin>: LibImages/LibImages.o] Error 1
  make[1]: *** [<builtin>: Utilities/Memory.o] Error 1
  g++: error: unrecognized command line option '--cflags`'
  g++: error: unrecognized command line option '--cflags`'
  make[1]: *** [<builtin>: main.o] Error 1
  make[1]: *** [<builtin>: LibHomography/Homography.o] Error 1
  make[1]: Leaving directory 'C:/Users/kumai/AppData/Local/Temp/pip-install-smqym8p9/s2p_2742f1c93e6845a78bcbda0fd22c8b3f/3rdparty/homography'
  make: *** [makefile:26: homography] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\kumai\AppData\Local\Temp\pip-install-smqym8p9\s2p_2742f1c93e6845a78bcbda0fd22c8b3f\setup.py", line 78, in <module>
      """)
    File "D:\Programs\Anaconda\envs\bunnies\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\Programs\Anaconda\envs\bunnies\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\kumai\AppData\Local\Temp\pip-install-smqym8p9\s2p_2742f1c93e6845a78bcbda0fd22c8b3f\setup.py", line 27, in run
      subprocess.check_call("make", shell=True)
    File "D:\Programs\Anaconda\envs\bunnies\lib\subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'make' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for s2p
  Running setup.py clean for s2p
  Building wheel for plyflatten (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\Programs\Anaconda\envs\bunnies\python.exe' 'D:\Programs\Anaconda\envs\bunnies\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\kumai\AppData\Local\Temp\tmp6sb6iwro'
       cwd: C:\Users\kumai\AppData\Local\Temp\pip-install-smqym8p9\plyflatten_495d5540656641ccb5fe3b74e952fa03
  Complete output (59 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\plyflatten
  copying plyflatten\cli.py -> build\lib\plyflatten
  copying plyflatten\rasterization.py -> build\lib\plyflatten
  copying plyflatten\utils.py -> build\lib\plyflatten
  copying plyflatten\__about__.py -> build\lib\plyflatten
  copying plyflatten\__init__.py -> build\lib\plyflatten
  mkdir -p lib
  cc  -fPIC -shared -o lib/libplyflatten.so src/plyflatten.c
  process_begin: CreateProcess(NULL, cc -fPIC -shared -o lib/libplyflatten.so src/plyflatten.c, ...) failed.
  make (e=2): The system cannot find the file specified.

  make: *** [Makefile:22: lib/libplyflatten.so] Error 2
  Traceback (most recent call last):
    File "D:\Programs\Anaconda\envs\bunnies\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 349, in <module>
      main()
    File "D:\Programs\Anaconda\envs\bunnies\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "D:\Programs\Anaconda\envs\bunnies\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 249, in build_wheel
      metadata_directory)
    File "C:\Users\kumai\AppData\Local\Temp\pip-build-env-k1rbzcml\overlay\Lib\site-packages\setuptools\build_meta.py", line 222, in build_wheel
      wheel_directory, config_settings)
    File "C:\Users\kumai\AppData\Local\Temp\pip-build-env-k1rbzcml\overlay\Lib\site-packages\setuptools\build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\kumai\AppData\Local\Temp\pip-build-env-k1rbzcml\overlay\Lib\site-packages\setuptools\build_meta.py", line 259, in run_setup
      self).run_setup(setup_script=setup_script)
    File "C:\Users\kumai\AppData\Local\Temp\pip-build-env-k1rbzcml\overlay\Lib\site-packages\setuptools\build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 66, in <module>
      cmdclass={"develop": CustomDevelop, "build_py": CustomBuildPy},
    File "C:\Users\kumai\AppData\Local\Temp\pip-build-env-k1rbzcml\overlay\Lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\kumai\AppData\Local\Temp\pip-build-env-k1rbzcml\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 39, in run
      subprocess.check_call("make lib", shell=True)
    File "D:\Programs\Anaconda\envs\bunnies\lib\subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'make lib' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for plyflatten
  Building wheel for srtm4 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\Programs\Anaconda\envs\bunnies\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kumai\\AppData\\Local\\Temp\\pip-install-smqym8p9\\srtm4_f3ce29b69bdd43d7aec806b766091854\\setup.py'"'"'; __file__='"'"'C:\\Users\\kumai\\AppData\\Local\\Temp\\pip-install-smqym8p9\\srtm4_f3ce29b69bdd43d7aec806b766091854\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\kumai\AppData\Local\Temp\pip-wheel-3wm6mpc0'
       cwd: C:\Users\kumai\AppData\Local\Temp\pip-install-smqym8p9\srtm4_f3ce29b69bdd43d7aec806b766091854\
  Complete output (52 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  copying srtm4.py -> build\lib
  running egg_info
  writing srtm4.egg-info\PKG-INFO
  writing dependency_links to srtm4.egg-info\dependency_links.txt
  writing requirements to srtm4.egg-info\requires.txt
  writing top-level names to srtm4.egg-info\top_level.txt
  reading manifest file 'srtm4.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'requirements.txt'
  writing manifest file 'srtm4.egg-info\SOURCES.txt'
  mkdir -p bin
  g++ -g -O3 -fpermissive -DNDEBUG -DDONT_USE_TEST_MAIN -c src/Geoid.cpp -o src/Geoid.o
  g++ -g -O3 -fpermissive -DNDEBUG -DDONT_USE_TEST_MAIN -c src/geoid_height_wrapper.cpp -o src/geoid_height_wrapper.o
  cc -std=c99 -g -O3 -DNDEBUG -DDONT_USE_TEST_MAIN -DMAIN_SRTM4 src/srtm4.c src/Geoid.o src/geoid_height_wrapper.o -lstdc++ -lz -lm -ltiff -o bin/srtm4
  process_begin: CreateProcess(NULL, cc -std=c99 -g -O3 -DNDEBUG -DDONT_USE_TEST_MAIN -DMAIN_SRTM4 src/srtm4.c src/Geoid.o src/geoid_height_wrapper.o -lstdc++ -lz -lm -ltiff -o bin/srtm4, ...) failed.
  make (e=2): The system cannot find the file specified.

  make: *** [Makefile:15: bin/srtm4] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\kumai\AppData\Local\Temp\pip-install-smqym8p9\srtm4_f3ce29b69bdd43d7aec806b766091854\setup.py", line 54, in <module>
      zip_safe=False)
    File "D:\Programs\Anaconda\envs\bunnies\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\Programs\Anaconda\envs\bunnies\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\kumai\AppData\Local\Temp\pip-install-smqym8p9\srtm4_f3ce29b69bdd43d7aec806b766091854\setup.py", line 28, in run
      subprocess.check_call("make", shell=True)
    File "D:\Programs\Anaconda\envs\bunnies\lib\subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'make' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for srtm4
  Running setup.py clean for srtm4
  Building wheel for ransac (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\Programs\Anaconda\envs\bunnies\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kumai\\AppData\\Local\\Temp\\pip-install-smqym8p9\\ransac_b5caa9701ef643008fa4e1e974c26cf6\\setup.py'"'"'; __file__='"'"'C:\\Users\\kumai\\AppData\\Local\\Temp\\pip-install-smqym8p9\\ransac_b5caa9701ef643008fa4e1e974c26cf6\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\kumai\AppData\Local\Temp\pip-wheel-_4a_uwda'
       cwd: C:\Users\kumai\AppData\Local\Temp\pip-install-smqym8p9\ransac_b5caa9701ef643008fa4e1e974c26cf6\
  Complete output (42 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  copying ransac.py -> build\lib
  The system cannot find the path specified.
  mkdir -p lib
  cc -march=native -O3 -mno-avx512f -std=gnu99 -fPIC -shared -o lib/libransac.so c/ransac.c
  process_begin: CreateProcess(NULL, cc -march=native -O3 -mno-avx512f -std=gnu99 -fPIC -shared -o lib/libransac.so c/ransac.c, ...) failed.
  make (e=2): The system cannot find the file specified.

  make: *** [Makefile:22: lib/libransac.so] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\kumai\AppData\Local\Temp\pip-install-smqym8p9\ransac_b5caa9701ef643008fa4e1e974c26cf6\setup.py", line 52, in <module>
      'build_py': CustomBuildPy})
    File "D:\Programs\Anaconda\envs\bunnies\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\Programs\Anaconda\envs\bunnies\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\Programs\Anaconda\envs\bunnies\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\kumai\AppData\Local\Temp\pip-install-smqym8p9\ransac_b5caa9701ef643008fa4e1e974c26cf6\setup.py", line 31, in run
      subprocess.check_call("make lib", shell=True)
    File "D:\Programs\Anaconda\envs\bunnies\lib\subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'make lib' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for ransac
  Running setup.py clean for ransac
Failed to build s2p plyflatten srtm4 ransac
ERROR: Could not build wheels for plyflatten which use PEP 517 and cannot be installed directly_
__

**Comment by Wsdnuaa** [comment]
I got the same problem when I installing s2p in ubuntu 20.04.But, it worked when I change the ubuntu version to 18.04.
