### ISSUE TITLE
install error:makefile:104: recipe for target 'c/iio.o' failed

### ISSUE THREAD

**Issue by Island19970226** [centreborelli/s2p#136]
After `pip install s2p`, when I test if S2P is correctly working using `make test`, it shows:
```
cp 3rdparty/lsd/lsd bin
cc -fpic -march=native -O3 -c c/iio.c -o c/iio.o
c/iio.c:1:1: error: expected identifier or ‘(’ before ‘.’ token
 ../3rdparty/iio/iio.c
 ^
c/iio.c:1:4: error: invalid suffix "rdparty" on integer constant
 ../3rdparty/iio/iio.c
    ^~~~~~~~
makefile:104: recipe for target 'c/iio.o' failed
make: *** [c/iio.o] Error 1
```
I also attempt to use `pip install -e ".[test]"`, but the same problem arises:
```
    cp 3rdparty/lsd/lsd bin
    cc -fpic -march=native -O3 -c c/iio.c -o c/iio.o
    c/iio.c:1:1: error: expected identifier or ‘(’ before ‘.’ token
     ../3rdparty/iio/iio.c
     ^
    c/iio.c:1:4: error: invalid suffix "rdparty" on integer constant
     ../3rdparty/iio/iio.c
        ^~~~~~~~
    makefile:104: recipe for target 'c/iio.o' failed
    make: *** [c/iio.o] Error 1
    /home/a/.local/lib/python3.6/site-packages/setuptools/dist.py:493: UserWarning: Normalizing '1.0b24dev' to '1.0b24.dev0'
      warnings.warn(tmpl.format(**locals()))
    /home/a/.local/lib/python3.6/site-packages/setuptools/command/easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
    /home/a/.local/lib/python3.6/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    /home/a/.local/lib/python3.6/site-packages/pkg_resources/__init__.py:119: PkgResourcesDeprecationWarning: 0.18ubuntu0.18.04.1 is an invalid version and will not be supported in a future release
      PkgResourcesDeprecationWarning,
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/a/software/s2p-master/setup.py", line 78, in <module>
        """)
      File "/home/a/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/a/software/s2p-master/setup.py", line 17, in run
        subprocess.check_call("make", shell=True)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'make' returned non-zero exit status 2.
    
    ----------------------------------------
  Rolling back uninstall of s2p
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/home/a/software/s2p-master/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=" failed with error code 1 in /home/a/software/s2p-master/

```
I am eager to know how I can solve this problem, thank you very much！

**Comment by mnhrdt** [comment]
Did you clone the repo together with its submodules?  Please try to do `git submodule update --init` if you didn't.

If the problem persists, please show us the output of the following commands (run inside the root of the s2p repo):

    uname -a
    cc --version
    ls -l c

**Comment by Island19970226** [comment]
> Did you clone the repo together with its submodules? Please try to do `git submodule update --init` if you didn't.
> 
> If the problem persists, please show us the output of the following commands (run inside the root of the s2p repo):
> 
> ```
> uname -a
> cc --version
> ls -l c
> ```

Thanks for your reply. I have cloned the repo together with its submodules,but the problem persists.The version of my ubuntu is 18.04 and python is 3.6.
```
a@a-virtual-machine:~/software/s2p-master$ make test
make -j -C 3rdparty/homography
make[1]: Entering directory '/home/a/software/s2p-master/3rdparty/homography'
make[1]: 'homography' is up to date.
make[1]: Leaving directory '/home/a/software/s2p-master/3rdparty/homography'
cp 3rdparty/homography/homography bin
make -j -C 3rdparty/sift/simd libsift4ctypes.so
make[1]: Entering directory '/home/a/software/s2p-master/3rdparty/sift/simd'
make[1]: 'libsift4ctypes.so' is up to date.
make[1]: Leaving directory '/home/a/software/s2p-master/3rdparty/sift/simd'
cp 3rdparty/sift/simd/libsift4ctypes.so lib
make -C 3rdparty/mgm_multi
make[1]: Entering directory '/home/a/software/s2p-master/3rdparty/mgm_multi'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/a/software/s2p-master/3rdparty/mgm_multi'
cp 3rdparty/mgm_multi/mgm       bin
cp 3rdparty/mgm_multi/mgm_multi bin
make -C 3rdparty/tvl1flow
make[1]: Entering directory '/home/a/software/s2p-master/3rdparty/tvl1flow'
make[1]: Nothing to be done for 'default'.
make[1]: Leaving directory '/home/a/software/s2p-master/3rdparty/tvl1flow'
cp 3rdparty/tvl1flow/tvl1flow bin
cp 3rdparty/tvl1flow/callTVL1.sh bin
make -C 3rdparty/lsd
make[1]: Entering directory '/home/a/software/s2p-master/3rdparty/lsd'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/a/software/s2p-master/3rdparty/lsd'
cp 3rdparty/lsd/lsd bin
cc -fpic -march=native -O3 -c c/iio.c -o c/iio.o
c/iio.c:1:1: error: expected identifier or ‘(’ before ‘.’ token
 ../3rdparty/iio/iio.c
 ^
c/iio.c:1:4: error: invalid suffix "rdparty" on integer constant
 ../3rdparty/iio/iio.c
    ^~~~~~~~
makefile:104: recipe for target 'c/iio.o' failed
make: *** [c/iio.o] Error 1
```

```
a@a-virtual-machine:~/software/s2p-master$ uname -a
Linux a-virtual-machine 4.15.0-202-generic #213-Ubuntu SMP Thu Jan 5 19:19:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
a@a-virtual-machine:~/software/s2p-master$ cc --version
cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```


```
a@a-virtual-machine:~/software/s2p-master$ ls -l c
total 180
-rwxrw-rw- 1 a a    39 11月 27  2020 abstract_dsf.c
-rwxrw-rw- 1 a a    35 11月 27  2020 backflow.c
-rwxrw-rw- 1 a a    34 11月 27  2020 bicubic.c
-rwxrw-rw- 1 a a    39 11月 27  2020 cldmask.c
-rwxrw-rw- 1 a a    39 11月 27  2020 colorcoordsf.c
-rwxrw-rw- 1 a a  9789 11月 27  2020 disp_to_h.c
-rwxrw-rw- 1 a a    33 11月 27  2020 downsa.c
-rwxrw-rw- 1 a a    38 11月 27  2020 drawsegment.c
-rwxrw-rw- 1 a a    31 11月 27  2020 fail.c
-rwxrw-rw- 1 a a    35 11月 27  2020 getpixel.c
-rwxrw-rw- 1 a a    37 11月 27  2020 help_stuff.c
-rwxrw-rw- 1 a a    21 11月 27  2020 iio.c
-rwxrw-rw- 1 a a    21 11月 27  2020 iio.h
-rwxrw-rw- 1 a a   912 11月 27  2020 lists.c
-rwxrw-rw- 1 a a  6142 11月 27  2020 morphoop.c
-rwxrw-rw- 1 a a    32 11月 27  2020 morsi.c
-rwxrw-rw- 1 a a    39 11月 27  2020 parsenumbers.c
-rwxrw-rw- 1 a a    34 11月 27  2020 pickopt.c
-rwxrw-rw- 1 a a    34 11月 27  2020 plambda.c
-rwxrw-rw- 1 a a  4148 11月 27  2020 plyextrema.c
-rwxrw-rw- 1 a a    32 11月 27  2020 pview.c
-rwxrw-rw- 1 a a    32 11月 27  2020 qauto.c
-rwxrw-rw- 1 a a    33 11月 27  2020 random.c
-rwxrw-rw- 1 a a  2462 11月 27  2020 read_matrix.c
-rwxrw-rw- 1 a a    47 11月 27  2020 remove_small_cc.c
-rwxrw-rw- 1 a a 19277 11月 27  2020 rpc.c
-rwxrw-rw- 1 a a  1234 11月 27  2020 rpc.h
-rwxrw-rw- 1 a a    32 11月 27  2020 smapa.h
-rwxrw-rw- 1 a a    33 11月 27  2020 spline.c
-rwxrw-rw- 1 a a  5795 11月 27  2020 timing.c
-rwxrw-rw- 1 a a  9311 11月 27  2020 timing.h
-rwxrw-rw- 1 a a    34 11月 27  2020 vvector.h
-rwxrw-rw- 1 a a    33 11月 27  2020 xfopen.c
-rwxrw-rw- 1 a a    34 11月 27  2020 xmalloc.c

```

**Comment by mnhrdt** [comment]
This is a strange error.  Is the filesystem where your repository resides mounted outside of the virtual machine?  It is as if symbolic links are not correctly seen by the filesystem.  Is that your case?  Then you may solve the problem by cloning the repository directly inside the virtual filesystem.

**Comment by Island19970226** [comment]
Thank you very much.  The reason seems to be that I downloaded the code in Windows  and copied it to Ubuntu. This problem was solved when I downloaded it inside the virtual filesystem.
