### ISSUE TITLE
Test error - subprocess.CalledProcessError: Command '['homography', ...] died with <Signals.SIGABRT: 6>

### ISSUE THREAD

**Issue by lucascdlima** [centreborelli/s2p#96]
Hi, I know that there is a closed topic regarding this problem however that topic actually didn't explain how to solve it (the mentioned topic moved to another issue).

I have tried to run the test command 
s2p tests/data/input_pair/config.json

and I got the following error:

rectifying tiles...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/user123/Doutorado/project/s2p/s2p/parallel.py", line 43, in tilewise_wrapper
    out = fun(*args)
  File "/home/user123/Doutorado/project/s2p/s2p/__init__.py", line 147, in rectification_pair
    H1, H2, disp_min, disp_max = rectification.rectify_pair(img1, img2,
  File "/home/user123/Doutorado/project/s2p/s2p/rectification.py", line 379, in rectify_pair
    common.image_apply_homography(out1, im1, H1, w0 + 2*hmargin, h0 + 2*vmargin)
  File "/home/user123/Doutorado/project/s2p/s2p/common.py", line 228, in image_apply_homography
    run(["homography", im, "-h", hij, out, "%d" % w, "%d" % h])
  File "/home/user123/Doutorado/project/s2p/s2p/common.py", line 92, in run
    subprocess.run(cmd, shell=shell, stdout=sys.stdout, stderr=sys.stderr,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['homography', '/home/user123/Doutorado/project/s2p/tests/data/input_pair/img_01.tif', '-h', '0.20884736403654167 -0.9784295099695219 477.88765037927976 0.9784295099695219 0.20884736403654167 -173.09153110090955 0.0 0.0 1.0', '/home/user123/Doutorado/project/s2p/tests/data/input_pair/../../testoutput/output_pair/tiles/row_0000150_height_350/col_0000150_width_350/pair_1/rectified_ref.tif', '455', '425']' died with <Signals.SIGABRT: 6>.
"""
I have tried two types of installation (from pip and compiling), the error still the same.
The automatic tests running command ( make test ) don't work either - same error regarding homography.

Python 3.8.10
Ubuntu 20.04.2 LTS

**Comment by Wsdnuaa** [comment]
I have the same problom, have you save this problom?

**Comment by fnands** [comment]
What version of gdal are you running? I get this with gdal >=3. 
So try gdal <=2.4.4
